### ISSUE TITLE
Access to DefaultSignalPayload

### ISSUE THREAD

**Issue by nevillco** [TelemetryDeck/SwiftClient#115]
I am trying out a project that uses TelemetryDeck analytics on iOS via this SDK and [on the backend](https://github.com/getsidetrack/vapor-telemetrydeck) via Vapor. It's working well and the combination of frontend/backend events allows for some clear insights/funnel analysis.

This SDK sends a number of default properties including `appVersion`, `buildNumber`, `isTestFlight`, `isAppStore` etc. via the [DefaultSignalPayload](https://github.com/TelemetryDeck/SwiftClient/blob/3f8bd438c8681ce7ccdf035b529cb5c4cd82cd7b/Sources/TelemetryClient/Signal.swift#L41). Several of these signals would be useful to pass to my backend events, but that's not currently possible because the associated values are `internal`. I would like to expose them to clients, but thought I'd start with an issue before a PR just because I'm not sure if it's something the maintainers want. Happy to raise a PR if it is.

**Comment by winsmith** [comment]
Oh yes please create a PR! Thank you :) 

BTW you might also consider checking out the dedicated Vapor SDK: https://github.com/getsidetrack/vapor-telemetrydeck

**Comment by nevillco** [comment]
Yep, I am using that on the backend, and it works great! I'd just like to have its events also contain a `appVersion`, `buildVersion`, `isAppStore` etc. like the client events do, hence this feature request. PR [here](https://github.com/TelemetryDeck/SwiftClient/pull/126).

**Comment by winsmith** [comment]
Fixed by https://github.com/TelemetryDeck/SwiftClient/pull/126
