### ISSUE TITLE
Use hashed deviceName + system version as default user identifier on macOS

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/SwiftClient#12]
```swift
if let deviceName = Host.current().localizedName {
   print(deviceName)
}
```

Currently, we only use system version on MacOS. This change will better distinguish users without endangering their privacy

**Comment by Jeehut** [comment]
@winsmith I just noticed this warning in my console for my macOS app:

```
[Telemetry] On this platform, Telemetry can't generate a unique user identifier. It is recommended you supply one yourself. More info: https://telemetrydeck.com/pages/signal-reference.html
```

From [this code](https://github.com/TelemetryDeck/SwiftClient/blob/2efe11d74f8c0318ee860831dd44ffb08196b3d5/Sources/TelemetryClient/SignalManager.swift#L215-L228) I derived that you're using [`identifierForVendor`](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) to retrieve a unique ID for the user. From what I understand, this ID provided by Apple behaves very much like a self-generated `UUID()` on first app start that was persisted somewhere accessible by the app. The only 2 differences to a self-generated `UUID` are:

1. The `UUID` is the same for all apps of the same vendor (on the same device).
2. The system takes care of persisting this `UUID` in behalf of the developer.

As such a thing is not available on macOS, I believe the closest thing to that would be a self-generated `UUID` based on nothing (no deviceName or system version needed). This UUID needs to be persisted and to not meddle with the developers data, I suggest using the [UserDefaults with a custom suitName](https://developer.apple.com/documentation/foundation/userdefaults/1409957-init) such as `TelemetryDeck` for that. This way TelemetryDeck could take care of persisting the default identifier in behalf of the developer. Overriding it of course should still be possible.

The last difference to `identifierForVendor` would then be that multiple apps of the same vendor on the same device would still have different unique identifiers. I suggest that this is covered by providing a hook the developer can opt-in to by passing the user defaults object of their [app group](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_application-groups) if they really want this behavior. By default, this would be the only difference to `identifierForVendor`.

The solution you suggest in my opinion is not safe to be unique. Two users with the same system and build version, and with the same name (e.g. "Daniel") and device could easily end up having the same identifier which could lead to a lot of confusion when tracking funnels, for example. I think, a persisted `UUID` is a better default here.

**Comment by winsmith** [comment]
I totally agree with your suggestion!

**Comment by Jeehut** [comment]
Alright, then expect a PR from me with my above outlined solution within a week or so.
