### ISSUE TITLE
Add support for usage through Server Side Swift

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/SwiftClient#20]
I just tried to setup TelemetryDeck on the Server (using Vapor) to track some anonymized events of my users API endpoint actions. One reason for this is that I take privacy seriously and therefore don't want to include any library that automatically accesses environment data if I can avoid it. This library for sure [does that](https://github.com/AppTelemetry/SwiftClient/blob/main/Sources/TelemetryClient/TelemetryClient.swift#L87-L99), so my preferred way to use TelemetryDeck is on the server side, where the environment doesn't provide any user-specific information. I already found out that I can set a user identifier manually, and I saw in the code that any additional payload fields can also override the ones automatically set. This way I will be able to control what data is being tracked of my users and to also implement [Differential Privacy](https://en.wikipedia.org/wiki/Differential_privacy) on my server if needed (as Telemetry doesn't support that yet).

But even with all these manual actions, this library seems still not to be prepared for Server-side usage as it's not only failing to [recognize Linux as a platform](https://github.com/AppTelemetry/SwiftClient/blob/main/Sources/TelemetryClient/TelemetryClient.swift#L252) automatically, but is also using [DispatchQueue](https://github.com/AppTelemetry/SwiftClient/blob/main/Sources/TelemetryClient/TelemetryClient.swift#L79) for doing asynchronous network calls, which I think is not the right way to go for a Vapor app. I'd expect some setting to run the network requests in an `EventLoop` instead (using Swift NIO).

@winsmith Do you have plans to add proper support for usage from the Server side? Or is this only intended for app clients?

**Comment by winsmith** [comment]
Hi Jeehut, these are all good points. I do intend to support server side telemetry as well, but it's not as high on my list of priorities as getting the desktop and mobile apps to a certain level of quality. I'll get around to it at some point, but if you want something quicker, you can totally fork this repo and use your own changes, or write a small library that implements [the spec](https://apptelemetry.io/pages/client-spec.html). I'll be happy to answer all your questions

**Comment by Sherlouk** [comment]
I have just published a Vapor package which adds support for TelemetryDeck signals: https://github.com/getsidetrack/vapor-telemetrydeck

It's fairly basic for now, but should have the essentials. Happy for you to raise feature requests via issues if you have extra requirements.

Let me know if this helps @Jeehut

**Comment by winsmith** [comment]
This is amazing and I love it! <3 Thank you

**Comment by winsmith** [comment]
Since @Sherlouk's package exists and works really well, I'm closing this ticket.
