### ISSUE TITLE
Cannot compile version 1.1.3 on macOS

### ISSUE THREAD

**Issue by biocross** [TelemetryDeck/SwiftClient#41]
I just upgraded from version 1.0.13 -> 1.1.3, and the SDK fails to compile. I'm using this for a macOS only app, and my deployment target is macOS 10.13+.

The error is in the file `Signal.swift` for an availability check for the property `isiOSAppOnMac`

```
isiOSAppOnMac' is only available in macOS 11.0 or newer
```

Versions upto `1.1.1` work fine. The issue starts with version `>= 1.1.2`.

**Comment by winsmith** [comment]
Yup, I *just* noticed the same thing in my build 😅 fix incoming

**Comment by winsmith** [comment]
https://github.com/TelemetryDeck/SwiftClient/releases/tag/1.1.4

**Comment by biocross** [comment]
Thank you for the quick fix!
