### ISSUE TITLE
Mac Catalyst apps running under TestFlight are reporting as production

### ISSUE THREAD

**Issue by mattcorey** [TelemetryDeck/SwiftClient#42]
Mac Catalyst apps that are running via TestFlight aren’t reporting as being TestFlight.  

Payload looks like:
isAppStore = true
isDebug = false
isSimulator = false
isTestFlight = false
operatingSystem = iOS (even though it’s on my Mac - probably just a Catalyst thing)
platform = macCatalyst
targetEnvironment = macCatalyst
systemVersion = macCatalyst 15.0

**Comment by winsmith** [comment]
This should be fixed in the next version with #62
