### ISSUE TITLE
Readme references SwiftClientTester project that does not exist 

### ISSUE THREAD

**Issue by xr1337** [TelemetryDeck/SwiftClient#49]
At the bottom of the Readme ( under Developing this SDK ) 
```
## Developing this SDK

Your PRs on TelemetryDeck's Swift Client are very much welcome. Check out the [SwiftClientTester](https://github.com/TelemetryDeck/SwiftClientTester) project, which provides a harness you can use to work on the library and try out new things.
```

The link `SwiftClientTester` points to a *non existing project* https://github.com/TelemetryDeck/SwiftClientTester

Expectation:
The link `SwiftClientTester` should redirect appropriately

**Comment by winsmith** [comment]
Whoops, thanks for noticing. The project was marked as private, but there's actually nothing in there that we wouldn't want to share I think. I made the project public, so the link should now work.
