### ISSUE TITLE
Default `newSessionBegan` signal doesn't fire when app starts

### ISSUE THREAD

**Issue by dvkch** [TelemetryDeck/SwiftClient#56]
Tested on iOS 15.4, with TelemetryDeck 1.1.6 : it seems the default signal is sent only when the notification `UIApplication.willEnterForegroundNotification` is received, but that one doesn't seem to be posted on app startup. Is this intended behavior ?

**Comment by winsmith** [comment]
This is intended behaviour for now, because our tutorials show you how to send a signal when the app launches. I realise that this is not very consistent behaviour however, and we'll rethink this in our next major version of the SDK.

**Comment by dvkch** [comment]
Alright, thank you for the clarification :)
