### ISSUE TITLE
Return correct model name on macOS

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/SwiftClient#60]
Right now we only return the model name when running the Swift SDK in macOS. Instead, it should return the hardware identifier. 

Using IOKit:

```swift
public func getMacModel() -> String? {
    let service = IOServiceGetMatchingService(kIOMasterPortDefault,
                                              IOServiceMatching("IOPlatformExpertDevice"))
    var modelIdentifier: String?

    if let modelData = IORegistryEntryCreateCFProperty(service, "model" as CFString, kCFAllocatorDefault, 0).takeRetainedValue() as? Data {
        if let modelIdentifierCString = String(data: modelData, encoding: .utf8)?.cString(using: .utf8) {
            modelIdentifier = String(cString: modelIdentifierCString)
        }
    }

    IOObjectRelease(service)
    return modelIdentifier
}
```

This will have to be gated with "if OS macOS" calls, so that the SDK still compiles for iOS and Linux.

**Comment by tonyarnold** [comment]
Did this make it into [7.23.0](https://github.com/getsentry/sentry-cocoa/releases/tag/7.23.0)?

**Comment by winsmith** [comment]
Sorry I don't have write access to sentry :D~ 

This is not in 1.1.6 but I'll add it to the upcoming 1.2 :)

**Comment by tonyarnold** [comment]
OMFG… it has been one of _those_ days. Sorry!
