### ISSUE TITLE
isAppStore seems to return true only when running via TestFlight

### ISSUE THREAD

**Issue by ralfebert** [TelemetryDeck/SwiftClient#75]
`Signal#isAppStore` seems to be wrong in the latest release - it checks for the app store receipt and only returns true if it is named 'sandboxReceipt' which is only the case when running via TestFlight...

https://github.com/TelemetryDeck/SwiftClient/blob/1b93eba467a55f1c2be6fe7d5c41b1bfbd389969/Sources/TelemetryClient/Signal.swift#L128

**Comment by winsmith** [comment]
Thanks! There have been wayyy to many problems with isAppStore, maybe it's time to retire that.

**Comment by Sherlouk** [comment]
This was fixed by https://github.com/TelemetryDeck/SwiftClient/commit/227570d973ddfda4f98e9d7064961eb8af036d7d right?

**Comment by winsmith** [comment]
Correct! Thanks!
