### ISSUE TITLE
Architecture reported incorrectly

### ISSUE THREAD

**Issue by biocross** [TelemetryDeck/SwiftClient#87]
Hello,

I'm using the SDK in a Mac app, and lately I've noticed:

1. The `architecture` graph has automatically switched to `modelName` attribute.
2. The architecture data is mixed with model name (see attached image)

<img width="352" alt="Screenshot 2023-01-25 at 2 56 34 PM" src="https://user-images.githubusercontent.com/840512/214500142-ad52886d-1c20-4d1a-a5b4-21f6c5dccfed.png">

This was an important data metric for me to track how many of my users were using Apple Silicon vs Intel. Is there something wrong with my query / graph configuration, or is this a bug in the SDK?

I'm using the library version 1.4.0

**Comment by winsmith** [comment]
Thanks for reporting this! I have some follow-up questions:

- Can you tell me your app ID please? I'll have a look at the database.
- Is the same problem happening on dashboard.telemetrydeck.com ?

**Comment by biocross** [comment]
1. App ID: `02DE950A-3143-4FC8-8293-8C08DB0EE78C` (unsure if this should be public 😅)
2. Yes, same issue on `dashboard.telemetrydeck.com`. Slick dashboard btw!

**Comment by winsmith** [comment]
Thanks, I'm investigating! 

The dashboard is the canonical way for TelemetryDeck now -- right now we don't have the bandwidth to work on the desktop app, so new features only land on dashboard.telemetrydeck.com

The app ID is not a strong secret, but if you'd like, edit your post to remove it, now that I've copied it. Can't hurt :)

**Comment by winsmith** [comment]
Okay so the insight had `modelname` as the breakdown property, so it's not surprising that it did show model names. What *is* surprising is that it did mix model names and architectures in your screenshot, so there's clearly something going on here. 

I switched the insight back to using `architecture` as its breakdown key and it should work as expected again. In the meantime I'll see if I can find a bug that could have caused this. Let me know if you have further troubles with this please! 😊
