### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by chrisvasselli** [TelemetryDeck/SwiftClient#90]
I prefer CocoaPods over SwiftPM. It would be great if TelemetryDeck had a Podspec and supported integration via CocoaPods!

**Comment by chrisvasselli** [comment]
I have actually put together a podspec, which I am happy to share if you'd like.

**Comment by winsmith** [comment]
Oh yes please do share it! We'll have a look and see if we can integrate it 👀

**Comment by chrisvasselli** [comment]
@winsmith created a PR 🙂 https://github.com/TelemetryDeck/SwiftClient/pull/91

**Comment by winsmith** [comment]
You're amazing! Thank you!
